extends SceneTree

const MAIN_SCENE := preload("res://Main3D.tscn")
const DISCLAIMER := "AUTOMATED_SCREENSHOT_ARTIFACT_NOT_MANUAL_VISUAL_TEST"

var output_directory: String = "res://builds/automated-screenshots"


func _initialize() -> void:
	for argument in OS.get_cmdline_user_args():
		if argument.begins_with("--output="):
			output_directory = argument.trim_prefix("--output=")
	call_deferred("_capture_suite")


func _capture_suite() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(output_directory))
	var root := MAIN_SCENE.instantiate()
	get_root().add_child(root)
	current_scene = root
	for frame in range(5):
		await process_frame
	var time_controller := root.get_node("Systems/TimeOfDayController")
	var profiles := [
		{"index":0, "file":"morning.png"},
		{"index":1, "file":"day.png"},
		{"index":2, "file":"evening.png"},
		{"index":3, "file":"night.png"},
	]
	for profile in profiles:
		time_controller.apply_preset(profile["index"])
		await _capture(root, profile["file"])
	time_controller.apply_preset(1)
	var plots := get_nodes_in_group("growwise_plot")
	if not plots.is_empty():
		plots[10].interact(root.get_node("World3D/Player"))
	await _capture(root, "selected_plot.png")
	root.get_node("CameraRig").set_zoom(22.0)
	await _capture(root, "npc_overview.png")
	var manifest := FileAccess.open(output_directory.path_join("MANIFEST.txt"), FileAccess.WRITE)
	manifest.store_line(DISCLAIMER)
	manifest.store_line("Generated by Godot automation; does not prove manual visual acceptance.")
	manifest.store_line("morning.png\nday.png\nevening.png\nnight.png\nselected_plot.png\nnpc_overview.png")
	manifest.close()
	print("GROWWISE3D_AUTOMATED_SCREENSHOTS_OK")
	quit(0)


func _capture(root: Node, file_name: String) -> void:
	for frame in range(3):
		await process_frame
	RenderingServer.force_draw(false)
	await process_frame
	var image := root.get_viewport().get_texture().get_image()
	var error := image.save_png(output_directory.path_join(file_name))
	if error != OK:
		push_error("Screenshot save failed for %s: %s" % [file_name, error_string(error)])
		quit(1)
